# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfazes\.ui\home_gestor_eventos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(20, 20, 20, 20)
        self.mainLayout.setSpacing(18)
        self.mainLayout.setObjectName("mainLayout")
        self.headerFrame = QtWidgets.QFrame(self.centralwidget)
        self.headerFrame.setStyleSheet("background-color:#1E73E8; border-radius:6px;")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.headerFrame.setObjectName("headerFrame")
        self.headerLayout = QtWidgets.QHBoxLayout(self.headerFrame)
        self.headerLayout.setContentsMargins(16, 14, 16, 14)
        self.headerLayout.setObjectName("headerLayout")
        self.lblTitulo = QtWidgets.QLabel(self.headerFrame)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitulo.setObjectName("lblTitulo")
        self.headerLayout.addWidget(self.lblTitulo)
        self.mainLayout.addWidget(self.headerFrame)
        self.lblBienvenida = QtWidgets.QLabel(self.centralwidget)
        self.lblBienvenida.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBienvenida.setObjectName("lblBienvenida")
        self.mainLayout.addWidget(self.lblBienvenida)
        self.cardsLayout = QtWidgets.QHBoxLayout()
        self.cardsLayout.setContentsMargins(40, 10, 40, 10)
        self.cardsLayout.setSpacing(28)
        self.cardsLayout.setObjectName("cardsLayout")
        self.btnConsultar = QtWidgets.QPushButton(self.centralwidget)
        self.btnConsultar.setMinimumSize(QtCore.QSize(220, 200))
        self.btnConsultar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnConsultar.setStyleSheet("QPushButton{background:#ffffff; border:1px solid #d8d8d8; border-radius:14px; padding:12px; font-size:11pt;}\n"
"QPushButton:hover{background:#f4f4f4;}\n"
"QPushButton:pressed{background:#ededed;}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/prefijoNuevo/group.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConsultar.setIcon(icon)
        self.btnConsultar.setIconSize(QtCore.QSize(72, 72))
        self.btnConsultar.setObjectName("btnConsultar")
        self.cardsLayout.addWidget(self.btnConsultar)
        self.btnNuevo = QtWidgets.QPushButton(self.centralwidget)
        self.btnNuevo.setMinimumSize(QtCore.QSize(220, 200))
        self.btnNuevo.setStyleSheet("QPushButton{background:#ffffff; border:1px solid #d8d8d8; border-radius:14px; padding:12px; font-size:11pt;}\n"
"QPushButton:hover{background:#f4f4f4;}\n"
"QPushButton:pressed{background:#ededed;}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/prefijoNuevo/calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNuevo.setIcon(icon1)
        self.btnNuevo.setIconSize(QtCore.QSize(72, 72))
        self.btnNuevo.setObjectName("btnNuevo")
        self.cardsLayout.addWidget(self.btnNuevo)
        self.btnModificar = QtWidgets.QPushButton(self.centralwidget)
        self.btnModificar.setMinimumSize(QtCore.QSize(220, 200))
        self.btnModificar.setStyleSheet("QPushButton{background:#ffffff; border:1px solid #d8d8d8; border-radius:14px; padding:12px; font-size:11pt;}\n"
"QPushButton:hover{background:#f4f4f4;}\n"
"QPushButton:pressed{background:#ededed;}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/prefijoNuevo/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnModificar.setIcon(icon2)
        self.btnModificar.setIconSize(QtCore.QSize(72, 72))
        self.btnModificar.setObjectName("btnModificar")
        self.cardsLayout.addWidget(self.btnModificar)
        self.mainLayout.addLayout(self.cardsLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.mainLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gestor de Eventos - Los Super Nenes"))
        self.lblTitulo.setText(_translate("MainWindow", "<span style=\"color:white; font-size:20pt; font-weight:600;\">Gestor de Eventos - Los Super Nenes</span>"))
        self.lblBienvenida.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\"font-size:18pt; font-weight:600; color:#333333;\">Bienvenidos al Gestor de Eventos</span><br/><span style=\"font-size:18pt; font-weight:600; color:#333333;\">Super Nernes</span></p></body></html>"))
        self.btnConsultar.setToolTip(_translate("MainWindow", "Abrir la vista de consulta de eventos"))
        self.btnConsultar.setText(_translate("MainWindow", "Consultar Eventos"))
        self.btnNuevo.setToolTip(_translate("MainWindow", "Crear un nuevo evento"))
        self.btnNuevo.setText(_translate("MainWindow", "Nuevo Evento"))
        self.btnModificar.setToolTip(_translate("MainWindow", "Editar o eliminar eventos existentes"))
        self.btnModificar.setText(_translate("MainWindow", "Modificar Eventos"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
