# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfazes\.ui\home-evento-listado_mesas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EventoMesas(object):
    def setupUi(self, EventoMesas):
        EventoMesas.setObjectName("EventoMesas")
        EventoMesas.resize(930, 647)
        self.centralwidget = QtWidgets.QWidget(EventoMesas)
        self.centralwidget.setObjectName("centralwidget")
        self.vlMain = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vlMain.setContentsMargins(14, 12, 14, 12)
        self.vlMain.setObjectName("vlMain")
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setStyleSheet("QFrame#header{background:#1E73E8; border-radius:8px; padding:10px 14px;}\n"
"QLabel#titulo{color:white; font-size:20pt; font-weight:600;}")
        self.header.setObjectName("header")
        self.hlHeader = QtWidgets.QHBoxLayout(self.header)
        self.hlHeader.setObjectName("hlHeader")
        self.titulo = QtWidgets.QLabel(self.header)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.hlHeader.addWidget(self.titulo)
        self.vlMain.addWidget(self.header)
        self.lblTituloEvento = QtWidgets.QLabel(self.centralwidget)
        self.lblTituloEvento.setStyleSheet("QLabel{font-size:14pt; font-weight:600; color:#333; margin:6px 0;}")
        self.lblTituloEvento.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTituloEvento.setObjectName("lblTituloEvento")
        self.vlMain.addWidget(self.lblTituloEvento)
        self.frameMesas = QtWidgets.QFrame(self.centralwidget)
        self.frameMesas.setStyleSheet("QFrame#frameMesas{background:#eeeeee; border:1px solid #cfcfcf; border-radius:8px;}")
        self.frameMesas.setObjectName("frameMesas")
        self.vlMesas = QtWidgets.QVBoxLayout(self.frameMesas)
        self.vlMesas.setContentsMargins(10, 10, 10, 10)
        self.vlMesas.setObjectName("vlMesas")
        self.tablaMesas = QtWidgets.QTableWidget(self.frameMesas)
        self.tablaMesas.setRowCount(6)
        self.tablaMesas.setColumnCount(2)
        self.tablaMesas.setObjectName("tablaMesas")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaMesas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaMesas.setHorizontalHeaderItem(1, item)
        self.tablaMesas.horizontalHeader().setVisible(True)
        self.tablaMesas.horizontalHeader().setStretchLastSection(True)
        self.tablaMesas.verticalHeader().setVisible(False)
        self.vlMesas.addWidget(self.tablaMesas)
        self.vlMain.addWidget(self.frameMesas)
        self.hlButtons = QtWidgets.QHBoxLayout()
        self.hlButtons.setSpacing(12)
        self.hlButtons.setObjectName("hlButtons")
        self.btnExportarCSV = QtWidgets.QPushButton(self.centralwidget)
        self.btnExportarCSV.setStyleSheet("QPushButton{background:#e6eefb; color:#1E73E8; font-size:10.5pt; border:1px solid #b9cff6; border-radius:10px; padding:8px 16px;} QPushButton:hover{background:#d9e7fb;} QPushButton:pressed{background:#c9dcf7;}")
        self.btnExportarCSV.setObjectName("btnExportarCSV")
        self.hlButtons.addWidget(self.btnExportarCSV)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlButtons.addItem(spacerItem)
        self.btnVolver = QtWidgets.QPushButton(self.centralwidget)
        self.btnVolver.setStyleSheet("QPushButton{background:#e6eefb; color:#1E73E8; font-size:10.5pt; border:1px solid #b9cff6; border-radius:10px; padding:8px 16px;} QPushButton:hover{background:#d9e7fb;} QPushButton:pressed{background:#c9dcf7;}")
        self.btnVolver.setObjectName("btnVolver")
        self.hlButtons.addWidget(self.btnVolver)
        self.vlMain.addLayout(self.hlButtons)
        EventoMesas.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(EventoMesas)
        self.statusbar.setObjectName("statusbar")
        EventoMesas.setStatusBar(self.statusbar)

        self.retranslateUi(EventoMesas)
        QtCore.QMetaObject.connectSlotsByName(EventoMesas)

    def retranslateUi(self, EventoMesas):
        _translate = QtCore.QCoreApplication.translate
        EventoMesas.setWindowTitle(_translate("EventoMesas", "Gestor de Eventos - Los Super Nenes"))
        self.titulo.setText(_translate("EventoMesas", "Gestor de Eventos - Los Super Nenes"))
        self.lblTituloEvento.setText(_translate("EventoMesas", ""))
        item = self.tablaMesas.horizontalHeaderItem(0)
        item.setText(_translate("EventoMesas", "Mesa"))
        item = self.tablaMesas.horizontalHeaderItem(1)
        item.setText(_translate("EventoMesas", "Invitados"))
        self.btnExportarCSV.setText(_translate("EventoMesas", "Exportar a CSV"))
        self.btnVolver.setText(_translate("EventoMesas", "Volver"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EventoMesas = QtWidgets.QMainWindow()
    ui = Ui_EventoMesas()
    ui.setupUi(EventoMesas)
    EventoMesas.show()
    sys.exit(app.exec_())
